/** @format */

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import OurExpertise from "../components/ourExpertise";
import OurProject from "../components/ourProject";
import Batholic from "../components/batHolic";
import LoadingScreen from "../components/LoadingScreen";
import Testimonials from "../components/testimonials";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Contact from "../components/Contact";
import TransitionScreen from "../components/TransitionScreen";
import Imgs4 from "../components/Imgs4";
import ExampleComponent from "../components/ExampleComponent";
import Footer from "../components/Footer";

import MobileOurProject from "../components/Mobileourproject";
import About from "../components/About";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoadingScreen />
      <ExampleComponent />
      {/* <TransitionScreen /> */}
      {/* <Navbar />
      <Hero />
      <Imgs4 />
      <About />
      <OurExpertise /> */}
      {/* <OurProject /> */}
      {/* <Testimonials />
      <Contact />
      <Footer /> */}
      <Batholic />
      {/* <MobileOurProject /> */}
      {/* <Hero /> */}
      {/* <div className="w-full flex justify-center">
        <About />
      </div> */}
      {/* <Contact /> */}
    </>
  );
}
